#!/usr/bin/env bash

mkdir -p user_instances

echo "Downloading B0 archive..."
wget "https://download1589.mediafire.com/ow1eghgm2xlgaE0q1Hl_E37TlnPC-FYIGjKdOPlHK4Lu9-XAoOwA7IWm25G6K0jpMHEfyoy-JL2dUu_45YDYEvi2f6P_wYMChomRyO9DMs8yzgIyvD0JWm47ASAWVGdqIRYvZN5V1B2je_UtUETZbZZVI5UvT4V7YXISjPc4ZicXfck/52mw2hkbcmfpe83/b0.tar.gz" -O /tmp/b0.tar.gz

if [ $? -ne 0 ]; then
    echo "Failed to download b0 archive!"
    exit 1
fi

echo "Extracting archive to user_instances..."
tar xzf /tmp/b0.tar.gz -C user_instances/

if [ $? -ne 0 ]; then
    echo "Failed to extract B0 archive!"
    rm -f /tmp/b0.tar.gz
    exit 1
fi

rm -f /tmp/b0.tar.gz

chmod -R u+rwX user_instances/

echo "B0 installation completed successfully!"
