aimbot.aimkey.button=Mouse5
aimbot.autoshoot=false
aimbot.debug.engine-pp=false
aimbot.projectile.enable=false
aimbot.vischeck-hitboxes=2
autojoin.auto-accept-q=true
autojoin.auto-queue=true
autojoin.auto-requeue=false
autojoin.class=1
autojoin.team=true
dc.enable=true
dc.restrict=false
dc.toggle-europe=true
cat-bot.abandon-if.humans-lte=10
cat-bot.always-crouch=true
cat-bot.anti-motd=true
cat-bot.autoqueue-report=true
cat-bot.autoreport.bypass-cooldown=true
cat-bot.enable=true
cfg.save=bot
crit.anti-crit=false
discord.enable=true
esp.enable=true
misc.autodisguise=false
misc.cheats-bypass=true
misc.engine-prediction=false
misc.insecure-bypass=true
name.namesteal.reconnect=false
nospread.center-cone=false
nospread.draw-info=false
